---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task-1
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the revision
      default: master
    - name: apikey
      description: the ibmcloud api key
    - name: api
      description: the ibmcloud api endpoint
      default: "https://cloud.ibm.com"
  workspaces:
  - name: task-pvc
    mountPath: /artifacts   
  steps:
    - name: execute-iam
      image: ibmcom/pipeline-base-image
      env:
        - name: REPOSITORY
          value: $(params.repository)
        - name: REVISION
          value: $(params.revision)
        - name: IBMCLOUD_API_KEY
          value: $(params.apikey)
        - name: API
          value: $(params.api)
        - name: HOME
          value: "/root"
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          ibmcloud login --apikey $IBMCLOUD_API_KEY --no-region;
          apt-get clean;
          apt-get -y install python3;
          ibmcloud logout;
          ibmcloud login --apikey $IBMCLOUD_API_KEY --no-region;
          cd /workspace;
          ls;
